package com.github.danilobandeira29.easy_funds.services;

public enum TransferEnum {
    TRANSFER_SELF_TRANSFER,
    TRANSFER_PAYER_NOT_FOUND,
    TRANSFER_PAYEE_NOT_FOUND,
    TRANSFER_PAYER_INSUFFICIENT_BALANCE,
    TRANSFER_UNAUTHORIZED,
    TRANSFER_PERSISTENCE_ERROR,
    TRANSFER_DEPOSIT_NEGATIVE_VALUE_FOR_PAYEE,
    TRANSFER_AUTHORIZATION,
    TRANSFER_AUTHORIZATION_ERROR
}
